//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidoSoap
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pedido", Namespace="http://schemas.datacontract.org/2004/07/dm113_pedidos.Model")]
    public partial class Pedido : object
    {
        
        private System.DateTime DataPedidoField;
        
        private int IdField;
        
        private PedidoSoap.ItemPedido[] ItemPedidoListField;
        
        private string NomeClienteField;
        
        private decimal TotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataPedido
        {
            get
            {
                return this.DataPedidoField;
            }
            set
            {
                this.DataPedidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PedidoSoap.ItemPedido[] ItemPedidoList
        {
            get
            {
                return this.ItemPedidoListField;
            }
            set
            {
                this.ItemPedidoListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeCliente
        {
            get
            {
                return this.NomeClienteField;
            }
            set
            {
                this.NomeClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemPedido", Namespace="http://schemas.datacontract.org/2004/07/dm113_pedidos.Model")]
    public partial class ItemPedido : object
    {
        
        private int IdItemPedidoField;
        
        private int IdPedidoField;
        
        private int IdProdutoField;
        
        private string NomeProdutoField;
        
        private decimal PrecoUnitarioField;
        
        private int QuantidadeField;
        
        private decimal TotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdItemPedido
        {
            get
            {
                return this.IdItemPedidoField;
            }
            set
            {
                this.IdItemPedidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPedido
        {
            get
            {
                return this.IdPedidoField;
            }
            set
            {
                this.IdPedidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProduto
        {
            get
            {
                return this.IdProdutoField;
            }
            set
            {
                this.IdProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeProduto
        {
            get
            {
                return this.NomeProdutoField;
            }
            set
            {
                this.NomeProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecoUnitario
        {
            get
            {
                return this.PrecoUnitarioField;
            }
            set
            {
                this.PrecoUnitarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantidade
        {
            get
            {
                return this.QuantidadeField;
            }
            set
            {
                this.QuantidadeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://schemas.datacontract.org/2004/07/dm113_pedidos.Model")]
    public partial class Produto : object
    {
        
        private string DescricaoField;
        
        private int IdProdutoField;
        
        private string NomeField;
        
        private decimal PrecoUnitarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                this.DescricaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProduto
        {
            get
            {
                return this.IdProdutoField;
            }
            set
            {
                this.IdProdutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecoUnitario
        {
            get
            {
                return this.PrecoUnitarioField;
            }
            set
            {
                this.PrecoUnitarioField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PedidoSoap.IPedidoService")]
    public interface IPedidoService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/ListarPedidos", ReplyAction="http://tempuri.org/IPedidoService/ListarPedidosResponse")]
        System.Threading.Tasks.Task<PedidoSoap.Pedido[]> ListarPedidosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/ObterPedidoPorId", ReplyAction="http://tempuri.org/IPedidoService/ObterPedidoPorIdResponse")]
        System.Threading.Tasks.Task<PedidoSoap.Pedido> ObterPedidoPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/CriarPedido", ReplyAction="http://tempuri.org/IPedidoService/CriarPedidoResponse")]
        System.Threading.Tasks.Task<int> CriarPedidoAsync(PedidoSoap.Pedido pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/AtualizarPedido", ReplyAction="http://tempuri.org/IPedidoService/AtualizarPedidoResponse")]
        System.Threading.Tasks.Task AtualizarPedidoAsync(PedidoSoap.Pedido pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/ExcluirPedido", ReplyAction="http://tempuri.org/IPedidoService/ExcluirPedidoResponse")]
        System.Threading.Tasks.Task ExcluirPedidoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/AdicionarItemAoPedido", ReplyAction="http://tempuri.org/IPedidoService/AdicionarItemAoPedidoResponse")]
        System.Threading.Tasks.Task AdicionarItemAoPedidoAsync(int pedidoId, PedidoSoap.ItemPedido item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/RemoverItemDoPedido", ReplyAction="http://tempuri.org/IPedidoService/RemoverItemDoPedidoResponse")]
        System.Threading.Tasks.Task RemoverItemDoPedidoAsync(int pedidoId, int itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/AtualizarItemDoPedido", ReplyAction="http://tempuri.org/IPedidoService/AtualizarItemDoPedidoResponse")]
        System.Threading.Tasks.Task AtualizarItemDoPedidoAsync(int pedidoId, PedidoSoap.ItemPedido item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/ListarItensDoPedido", ReplyAction="http://tempuri.org/IPedidoService/ListarItensDoPedidoResponse")]
        System.Threading.Tasks.Task<PedidoSoap.ItemPedido[]> ListarItensDoPedidoAsync(int pedidoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/ListarPedidosPorStatus", ReplyAction="http://tempuri.org/IPedidoService/ListarPedidosPorStatusResponse")]
        System.Threading.Tasks.Task<PedidoSoap.Pedido[]> ListarPedidosPorStatusAsync(string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/ListarPedidosPorCliente", ReplyAction="http://tempuri.org/IPedidoService/ListarPedidosPorClienteResponse")]
        System.Threading.Tasks.Task<PedidoSoap.Pedido[]> ListarPedidosPorClienteAsync(string nomeCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/ListarPedidosPorData", ReplyAction="http://tempuri.org/IPedidoService/ListarPedidosPorDataResponse")]
        System.Threading.Tasks.Task<PedidoSoap.Pedido[]> ListarPedidosPorDataAsync(System.DateTime dataInicial, System.DateTime dataFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/ListarProdutos", ReplyAction="http://tempuri.org/IPedidoService/ListarProdutosResponse")]
        System.Threading.Tasks.Task<PedidoSoap.Produto[]> ListarProdutosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/ObterProdutoPorId", ReplyAction="http://tempuri.org/IPedidoService/ObterProdutoPorIdResponse")]
        System.Threading.Tasks.Task<PedidoSoap.Produto> ObterProdutoPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/CriarProduto", ReplyAction="http://tempuri.org/IPedidoService/CriarProdutoResponse")]
        System.Threading.Tasks.Task<int> CriarProdutoAsync(PedidoSoap.Produto produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/AtualizarProduto", ReplyAction="http://tempuri.org/IPedidoService/AtualizarProdutoResponse")]
        System.Threading.Tasks.Task AtualizarProdutoAsync(PedidoSoap.Produto produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoService/ExcluirProduto", ReplyAction="http://tempuri.org/IPedidoService/ExcluirProdutoResponse")]
        System.Threading.Tasks.Task ExcluirProdutoAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IPedidoServiceChannel : PedidoSoap.IPedidoService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class PedidoServiceClient : System.ServiceModel.ClientBase<PedidoSoap.IPedidoService>, PedidoSoap.IPedidoService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PedidoServiceClient() : 
                base(PedidoServiceClient.GetDefaultBinding(), PedidoServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPedidoService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PedidoServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PedidoServiceClient.GetBindingForEndpoint(endpointConfiguration), PedidoServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PedidoServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PedidoServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PedidoServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PedidoServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PedidoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<PedidoSoap.Pedido[]> ListarPedidosAsync()
        {
            return base.Channel.ListarPedidosAsync();
        }
        
        public System.Threading.Tasks.Task<PedidoSoap.Pedido> ObterPedidoPorIdAsync(int id)
        {
            return base.Channel.ObterPedidoPorIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<int> CriarPedidoAsync(PedidoSoap.Pedido pedido)
        {
            return base.Channel.CriarPedidoAsync(pedido);
        }
        
        public System.Threading.Tasks.Task AtualizarPedidoAsync(PedidoSoap.Pedido pedido)
        {
            return base.Channel.AtualizarPedidoAsync(pedido);
        }
        
        public System.Threading.Tasks.Task ExcluirPedidoAsync(int id)
        {
            return base.Channel.ExcluirPedidoAsync(id);
        }
        
        public System.Threading.Tasks.Task AdicionarItemAoPedidoAsync(int pedidoId, PedidoSoap.ItemPedido item)
        {
            return base.Channel.AdicionarItemAoPedidoAsync(pedidoId, item);
        }
        
        public System.Threading.Tasks.Task RemoverItemDoPedidoAsync(int pedidoId, int itemId)
        {
            return base.Channel.RemoverItemDoPedidoAsync(pedidoId, itemId);
        }
        
        public System.Threading.Tasks.Task AtualizarItemDoPedidoAsync(int pedidoId, PedidoSoap.ItemPedido item)
        {
            return base.Channel.AtualizarItemDoPedidoAsync(pedidoId, item);
        }
        
        public System.Threading.Tasks.Task<PedidoSoap.ItemPedido[]> ListarItensDoPedidoAsync(int pedidoId)
        {
            return base.Channel.ListarItensDoPedidoAsync(pedidoId);
        }
        
        public System.Threading.Tasks.Task<PedidoSoap.Pedido[]> ListarPedidosPorStatusAsync(string status)
        {
            return base.Channel.ListarPedidosPorStatusAsync(status);
        }
        
        public System.Threading.Tasks.Task<PedidoSoap.Pedido[]> ListarPedidosPorClienteAsync(string nomeCliente)
        {
            return base.Channel.ListarPedidosPorClienteAsync(nomeCliente);
        }
        
        public System.Threading.Tasks.Task<PedidoSoap.Pedido[]> ListarPedidosPorDataAsync(System.DateTime dataInicial, System.DateTime dataFinal)
        {
            return base.Channel.ListarPedidosPorDataAsync(dataInicial, dataFinal);
        }
        
        public System.Threading.Tasks.Task<PedidoSoap.Produto[]> ListarProdutosAsync()
        {
            return base.Channel.ListarProdutosAsync();
        }
        
        public System.Threading.Tasks.Task<PedidoSoap.Produto> ObterProdutoPorIdAsync(int id)
        {
            return base.Channel.ObterProdutoPorIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<int> CriarProdutoAsync(PedidoSoap.Produto produto)
        {
            return base.Channel.CriarProdutoAsync(produto);
        }
        
        public System.Threading.Tasks.Task AtualizarProdutoAsync(PedidoSoap.Produto produto)
        {
            return base.Channel.AtualizarProdutoAsync(produto);
        }
        
        public System.Threading.Tasks.Task ExcluirProdutoAsync(int id)
        {
            return base.Channel.ExcluirProdutoAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPedidoService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPedidoService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:5168/Service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PedidoServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPedidoService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PedidoServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPedidoService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IPedidoService,
        }
    }
}
